// Expo app configuration — the single source of truth for the native projects
// (android/ and ios/ are generated by `expo prebuild` and never committed).
//
// EXPO_PUBLIC_APP_ENV selects the variant. Each variant has its own Android
// package, name and deep-link scheme, so development, staging and production
// builds can be installed side by side on one phone. The same variable is read
// at runtime by src/config/env.js.
//
// Android first: iOS is not configured or built yet. The bundle identifier is
// reserved below so adding iOS later needs no change to the variant scheme.

const BASE_ID = 'in.khelscore.app';

const VARIANTS = Object.freeze({
  development: { idSuffix: '.dev', name: 'KhelScore Dev', scheme: 'khelscore-dev' },
  staging: { idSuffix: '.staging', name: 'KhelScore Staging', scheme: 'khelscore-staging' },
  production: { idSuffix: '', name: 'KhelScore', scheme: 'khelscore' },
});

// Brand surfaces (frontend/src/index.css: --color-bg light / dark).
const SPLASH_LIGHT = '#FAF8F5';
const SPLASH_DARK = '#090D16';
// All three are generated from the brand file by `node scripts/makeBrandAssets.js`:
// the square icon on white, the launcher foreground inside the adaptive-icon
// safe circle, and the transparent splash mark that sits on either surface.
const ICON = './assets/images/icon.png';
const ADAPTIVE_ICON = './assets/images/adaptive-icon.png';
const SPLASH_ICON = './assets/images/splash-icon.png';

// Permissions pulled in by libraries that this app never uses. Each one would
// have to be declared and defended on the Play data-safety form, so it is
// removed from the manifest instead.
//   SYSTEM_ALERT_WINDOW  — React Native's debug overlay (the dev menu still opens)
//   USE_BIOMETRIC / USE_FINGERPRINT — expo-secure-store's biometric mode; the
//     refresh token is stored with AFTER_FIRST_UNLOCK_THIS_DEVICE_ONLY instead
//   CHANGE_WIFI_MULTICAST_STATE — Metro's local network discovery; the app
//     reaches its server by URL
const BLOCKED_PERMISSIONS = [
  'android.permission.SYSTEM_ALERT_WINDOW',
  'android.permission.USE_BIOMETRIC',
  'android.permission.USE_FINGERPRINT',
  'android.permission.CHANGE_WIFI_MULTICAST_STATE',
];

// The website's host, and the paths the app opens instead of the browser. Each
// one is a screen of the app (src/app/…), so a shared link lands in the same
// place either way. Android only verifies these once the site serves
// /.well-known/assetlinks.json with this build's signing fingerprint; until
// then the links still work, but Android asks which app should open them.
const SITE_HOST = 'www.khelscore.in';
const LINKED_PATHS = ['/match/*', '/team/*', '/tournament/*', '/player/*', '/join', '/join/*'];

function resolveVariant() {
  const appEnv = process.env.EXPO_PUBLIC_APP_ENV ?? 'development';
  const variant = VARIANTS[appEnv];
  if (!variant) {
    throw new Error(
      `EXPO_PUBLIC_APP_ENV must be one of ${Object.keys(VARIANTS).join(', ')} (got "${appEnv}")`,
    );
  }
  return variant;
}

module.exports = () => {
  const { idSuffix, name, scheme } = resolveVariant();
  return {
    name,
    slug: 'khelscore',
    version: '0.1.0',
    scheme,
    orientation: 'portrait',
    userInterfaceStyle: 'automatic',
    icon: ICON,
    android: {
      package: `${BASE_ID}${idSuffix}`,
      adaptiveIcon: { foregroundImage: ADAPTIVE_ICON, backgroundColor: '#FFFFFF' },
      blockedPermissions: BLOCKED_PERMISSIONS,
      predictiveBackGestureEnabled: false,
      // App Links: the production app opens khelscore.in links itself. The
      // development and staging variants are left out on purpose — they are
      // not the app that site vouches for, and `scheme` still opens them.
      intentFilters: idSuffix
        ? []
        : [
            {
              action: 'VIEW',
              autoVerify: true,
              category: ['BROWSABLE', 'DEFAULT'],
              data: LINKED_PATHS.map((pathPrefix) => ({
                scheme: 'https',
                host: SITE_HOST,
                pathPrefix: pathPrefix.replace(/\/\*$/, ''),
              })),
            },
          ],
    },
    ios: {
      // Reserved for later; no iOS build is configured yet.
      bundleIdentifier: `${BASE_ID}${idSuffix}`,
    },
    plugins: [
      'expo-router',
      // Push notifications. Without an EAS project id and Firebase credentials
      // the app simply reports push unavailable (src/lib/push/expoPush.js).
      'expo-notifications',
      // Refresh token in the Android Keystore; auto-backup excludes it.
      ['expo-secure-store', { configureAndroidBackup: true }],
      // Profile photos come from the photo library only: no camera or microphone.
      ['expo-image-picker', { cameraPermission: false, microphonePermission: false }],
      [
        'expo-splash-screen',
        {
          image: SPLASH_ICON,
          imageWidth: 160,
          resizeMode: 'contain',
          backgroundColor: SPLASH_LIGHT,
          dark: { image: SPLASH_ICON, backgroundColor: SPLASH_DARK },
        },
      ],
    ],
  };
};
