// Expo app configuration — the single source of truth for the native projects
// (android/ and ios/ are generated by `expo prebuild` and never committed).
//
// EXPO_PUBLIC_APP_ENV selects the variant. Each variant has its own Android
// package, name and deep-link scheme, so development, staging and production
// builds can be installed side by side on one phone. The same variable is read
// at runtime by src/config/env.js.
//
// Android first: iOS is not configured or built yet. The bundle identifier is
// reserved below so adding iOS later needs no change to the variant scheme.

const BASE_ID = 'in.khelscore.app';

const VARIANTS = Object.freeze({
  development: { idSuffix: '.dev', name: 'KhelScore Dev', scheme: 'khelscore-dev' },
  staging: { idSuffix: '.staging', name: 'KhelScore Staging', scheme: 'khelscore-staging' },
  production: { idSuffix: '', name: 'KhelScore', scheme: 'khelscore' },
});

// Brand surfaces (frontend/src/index.css: --color-bg light / dark).
const SPLASH_LIGHT = '#FAF8F5';
const SPLASH_DARK = '#090D16';
const ICON = './assets/images/icon.png';

function resolveVariant() {
  const appEnv = process.env.EXPO_PUBLIC_APP_ENV ?? 'development';
  const variant = VARIANTS[appEnv];
  if (!variant) {
    throw new Error(
      `EXPO_PUBLIC_APP_ENV must be one of ${Object.keys(VARIANTS).join(', ')} (got "${appEnv}")`,
    );
  }
  return variant;
}

module.exports = () => {
  const { idSuffix, name, scheme } = resolveVariant();
  return {
    name,
    slug: 'khelscore',
    version: '0.1.0',
    scheme,
    orientation: 'portrait',
    userInterfaceStyle: 'automatic',
    icon: ICON,
    android: {
      package: `${BASE_ID}${idSuffix}`,
      adaptiveIcon: { foregroundImage: ICON, backgroundColor: '#FFFFFF' },
      predictiveBackGestureEnabled: false,
    },
    ios: {
      // Reserved for later; no iOS build is configured yet.
      bundleIdentifier: `${BASE_ID}${idSuffix}`,
    },
    plugins: [
      'expo-router',
      [
        'expo-splash-screen',
        {
          image: ICON,
          imageWidth: 160,
          resizeMode: 'contain',
          backgroundColor: SPLASH_LIGHT,
          dark: { image: ICON, backgroundColor: SPLASH_DARK },
        },
      ],
    ],
  };
};
